// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdfcelsjfqilmiojowix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkZmNlbHNqZnFpbG1pb2pvd2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNjc3MzIsImV4cCI6MjA3Nzg0MzczMn0.0exXVB14MR9Qac_e077SMn-CrL6LQHbhvkm1zw0ePOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});